### ISSUE TITLE
ssh: handshake failed: knownhosts: key mismatch

### ISSUE THREAD

**Issue by loic-roux-404** [manala/manala#18]
Using github enterprise repo, with my simple ssh key pair (id_rsa & pub)

After ` $(eval ssh-agent -s) && ssh-add` on Linux (centos 6)

`manala up` give : `ssh: handshake failed: knownhosts: key mismatch`

git clone works

I think you should now use `"github.com/go-git/go-git"` (v5)  instead of `gopkg.in/src-d/go-git.v4`

**Comment by nervo** [comment]
Ah, i've just checked that yesterday and did'nt see a new v5 version :)
I can build a testing version, what's your platform ?

**Comment by loic-roux-404** [comment]
v5 isn't it `"github.com/go-git/go-git/v5"` ? it's on the project [README.md](https://github.com/go-git/go-git#installation)

I use a binary on linux centos6.7 `x86_64` (don't have a lot infos for now)

I also tried on cygwin (Windows 10), but it's another error (go-git search pageant ssh-agent)

On my Mac Os Catalina 10.15 (last manala version on homebrew) it give : `stat git@github.com/loic-roux-404:manala-recipes: no such file or directory`

It looks like very difficult to do a manala update from a remote repo

**Comment by nervo** [comment]
1) Please tell me exactly what did you do to receive such a message (`stat git@github.com/loic-roux-404:manala-recipes: no such file or directory`)
2) What do you mean by "Its look like very difficult to do a manala update from a remote repo" ? What did you try ? What was the results ?

**Comment by nervo** [comment]
@loic-roux-404 here are some new binaries https://we.tl/t-iA1cJqo2CN
Please, test them, and tell me everything :)

**Comment by loic-roux-404** [comment]
> 1. Please tell me exactly what did you do to receive such a message (`stat git@github.com/loic-roux-404:manala-recipes: no such file or directory`) It looks like a typo `github.com/loic-roux-404:manala-recipes`-> `github.com/loic-roux-404/manala-recipes`

I try all possible urls like http  http://github.com/loic-roux-404/manala-recipes and ssh git@github.com/loic-roux-404/manala-recipes like you tell me but on **mac os** it's not working

I followed this [doc](https://manala.github.io/manala/overview/)

```
manala:
  repository: git@github.com:loic-roux-404/manala-recipes 
  recipe: ops.playbook
```

> 2. What do you mean by "Its look like very difficult to do a manala update from a remote repo" ? What did you try ? What was the results ?

Just the fact the `manala up` isn't platform agnostic, it doesn't have the same behaviour depending on platform

- On mac it seems managing the url in `.manala.yaml` like a folder on my machine.
- On linux, the git plugin can't get ssh environment correctly (authorized keys / private keys / know hosts)
- On Windows : we need pageant ssh-agent, i didn't try it for now

**Comment by loic-roux-404** [comment]
- Tried your patched binary on mac, still same error (stat folder)
- I try on cygwin and centos monday the other binary

**Comment by nervo** [comment]
1) ok, i get it :) The url of your repository must be just the same as the one you use to clone it, `git@github.com:loic-roux-404/manala-recipes.git`. I will fix the documentation accordingly.
2.1) Let's consider it's no longer an issue on mac
2.2) If you're talking about ` ssh: handshake failed: knownhosts: key mismatch` i suspect a typo in your ssh `knownhosts` file. Please check it twice.
3.3) I must admit i've never tried on windows :) I guess a ssh agent is required, just like on linux or mac os...

**Comment by loic-roux-404** [comment]
Sorry for the time to answer 😄 

ok, i get it :) The url of your repository must be just the same as the one you use to clone it, git@github.com:loic-roux-404/manala-recipes.git. I will fix the documentation accordingly.

Look like my exotic shell (fish) was causing ssh-agent issues, work perfectly now with simple bash. I think it can works with this type of [tool](https://github.com/danhper/fish-ssh-agent) for fish...

>2.2) If you're talking about ssh: handshake failed: knownhosts: key mismatch i suspect a typo in your ssh knownhosts file. > Please check it twice.

I'm not sure if there is a typo in the file, with simple `git fetch` command on centos it works correctly. I had refreshed the file in case but same error. I should try in a more sane linux environment (centos 6 is a little old).
I think it's can be difficult to fix it because usage comes from go-git dependency and look like a known problem.

> I must admit i've never tried on windows :) I guess a ssh agent is required, just like on linux or mac os...
3. On windows cygwin i think it's going to be difficult to make this works...

**Comment by nervo** [comment]
1) Well, it's not directly related to your shell, but yes, if you don't start your ssh-agent, you will soon or later encounter issues :)
2) Check if you have empty lines in your known host, for instance
3) Why exactly using cygwin ? Why not wsl ?

**Comment by loic-roux-404** [comment]
> 1. Well, it's not directly related to your shell, but yes, if you don't start your ssh-agent, you will soon or later encounter issues

Yes, of course but fish didn't started correctly the `ssh-agent` despite of the usage of `eval (ssh-agent -c)`.

> 2.
I will try on monday for `known host` when i get access to my work laptop.

> 3. Why exactly using cygwin ? Why not wsl ?

I prefer keep a windows only environment because :
- I like the concept of just keep unix organisation by keeping windows binaries and transfer of env vars
- i'm using vagrant with VM on centos.  WSL is difficult to configure with vagrant / virtualbox.
- I can keep the same filesystem as windows...

Probably i should try WSL 2 which can be clothe to the usage i have of cygwin but i never get enough time to try fully (i'm on mac / linux at home)

**Comment by loic-roux-404** [comment]
All work now...
