### ISSUE TITLE
Recipe lock / version

### ISSUE THREAD

**Issue by maximecolin** [manala/manala#19]
It will be great to being able to lock a recipe on a particular version (commit should be fine). Actually, if the recipe is modified, BC break can be introduced. Then I can't run `manala up` anymore without updating the `.manala.yaml` to the new config format. This is a problem.

I'm thinking changing a bit how the `manala up` works. At the first call, it will generate a `.manala.lock` containing the recipe commit hash. Then `manala up` will always use this version of the recipe. A new command or option will allow you update this lock to the last version.

Alternative: we can keep the actual `manala up` behavior and activate the lock behavior with the option `--lock` on the first `manala up` call.

I have the following use-cases in mind:

- You are developing a feature on your project that require to update something in `.manala.yaml` and the recipe has been updated in a way you can't `manala up`. The fix of the manala config should be done in a dedicated PR, not in your feature one.
- You need to update an old project, the recipe has to many changes so you can't or you won't fix the config.

**Comment by nervo** [comment]
@maximecolin i have this one on mind for a long time :)
But my first thought was not to use the `lock` paradigm, something more like define the version (git tag/hash/branch/...) in the .manala.yaml

```
manala:
    recipe: prout.prout
    version: 21b7a49
```

or npm/composer/whatever style
```
manala:
    recipe: prout.prout:21b7a49
```

How do you feel about it ?

**Comment by maximecolin** [comment]
It will solve my problem too :)

**Comment by nervo** [comment]
And not (so) hard to implement :)

**Comment by nervo** [comment]
Fixed by https://github.com/manala/manala/pull/65
